services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]  # keep changelog persistent
    ports: ["6380:6379"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
  
  # mysql:
  #   image: mysql:8.4
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
  #     MYSQL_DATABASE: ${MYSQL_DB}
  #   ports:
  #     - "3306:3306"     # or "3307:3306" if 3306 is busy on host
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_PASS}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 20

  trending:
    build: .
    image: token-pipeline:latest
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      TZ: ${TZ}
      REDIS_URL: redis://redis:6379/0
    command: ["python", "-u", "new-token-extractor-redis.py"]
    restart: unless-stopped

  trader:
    build: .
    depends_on:
      # mysql:
      #   condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      REDIS_URL: ${REDIS_URL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB:   ${MYSQL_DB}
      DB_URL: ${AIVEN_DATABASE_URL}
    command: ["python", "-u", "trader-extractor-redis.py"]
    restart: unless-stopped

volumes:
  mysqldata:
  redisdata: